Testing indexing logic

In [64]:
import torch
torch.set_printoptions(threshold=1000)

In [68]:
N = 1
SEQ = 1024
WIDTH = 1536
NUM_HEADS = 16
HEAD_DIM = WIDTH // NUM_HEADS
print(f"N: {N}, SEQ: {SEQ}, WIDTH: {WIDTH}, NUM_HEADS: {NUM_HEADS}, HEAD_DIM: {HEAD_DIM}")

N: 1, SEQ: 1024, WIDTH: 1536, NUM_HEADS: 16, HEAD_DIM: 96


In [87]:
torch.manual_seed(42)
x = torch.rand((N,NUM_HEADS,SEQ,HEAD_DIM))
y = x.permute((0,2,1,3))
y = y.reshape((N,SEQ,NUM_HEADS*HEAD_DIM))

In [88]:
print(x[0,0,0,:]) # This is 0th head embeding of the 0th sequence
print(x[0,1,0,:])

tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332, 0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739,
        0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588,
        0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090,
        0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644, 0.7104, 0.9464, 0.7890,
        0.2814, 0.7886, 0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103,
        0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315, 0.1587, 0.6542,
        0.3278, 0.6532, 0.3958, 0.9147, 0.2036, 0.2018, 0.2018, 0.9497, 0.6666,
        0.9811, 0.0874, 0.0041, 0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418,
        0.1591, 0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477, 0.6524,
        0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331])
tensor([0.7329, 0.4271, 0.3459, 0.3848, 0.5247, 0.9524, 0.9784, 0.0528, 0.0581,
        0.1591, 0.3134, 0.3448, 0.7906, 0.0428, 0.9987, 0.2839,

In [89]:
torch.set_printoptions(threshold=10000) # Set a high threshold

print(y[0,0,:96]) # This is all the heads in the 0th sequence. WIDTH // HEAD_IDX = 96 each
print(y[0,0,96:192]) # This is all the heads in the 0th sequence. WIDTH // HEAD_IDX = 96 each

tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332, 0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739,
        0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588,
        0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090,
        0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644, 0.7104, 0.9464, 0.7890,
        0.2814, 0.7886, 0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103,
        0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315, 0.1587, 0.6542,
        0.3278, 0.6532, 0.3958, 0.9147, 0.2036, 0.2018, 0.2018, 0.9497, 0.6666,
        0.9811, 0.0874, 0.0041, 0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418,
        0.1591, 0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477, 0.6524,
        0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331])
tensor([0.7329, 0.4271, 0.3459, 0.3848, 0.5247, 0.9524, 0.9784, 0.0528, 0.0581,
        0.1591, 0.3134, 0.3448, 0.7906, 0.0428, 0.9987, 0.2839,

In [97]:
z = y.reshape((N,SEQ,NUM_HEADS,HEAD_DIM)).permute((0,2,1,3))
(x-z).mean()

tensor(0.)